name: Karbala-Final-Success
on:
  workflow_dispatch:
jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Start
        run: |
          while true; do
            ffmpeg -re -i "https://ssh101.com/hls/karbalatv/playlist.m3u8" \
            -c:v libx264 -preset ultrafast -b:v 1500k -c:a aac -f flv "rtmp://a.rtmp.youtube.com/live2/bxv1-229e-2p3p-j3fb-9rfp"
            sleep 10
          done
