name: Aloush Clean Stream

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          pip3 install yt-dlp

      - name: Start Black Stream
        env:
          STREAM_KEY: "q12g-s6wc-0y03-0ua5-6e6p"
          VIDEO_ID: "9cauMvs6aYQ"
        run: |
          while true; do
            url=$(yt-dlp -g -f "best" "https://www.youtube.com/watch?v=$VIDEO_ID")
            ffmpeg -re -i "$url" -c:v libx264 -preset fast -b:v 2000k -c:a aac -b:a 128k -f flv "rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY"
            sleep 5
          done
